dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'complexpassword'"
  - psql -U postgres -c "create database decidedb owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - cd decide
  - python manage.py test --keepdb 
branches:
   only:
     - master
notifications:
  slack:
    on_success: never
    on_failure: never
deploy:
  provider: heroku
  app: testexamfraalepal
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN
  on:
    branch: master
